services:
  gateway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on: [node-a, node-b, node-c]
    networks: [mesh]

  node-a:
    build: .
    environment:
      - NODE_ID=node-a
      - REGION_CODE=RU-MOW
      - PEERS=http://node-b:8080,http://node-c:8080
      - AI_BASE_URL=https://openrouter.ai/api/v1
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=deepseek/deepseek-chat
    volumes:
      - ./data/node-a:/app/data
    networks: [mesh]

  node-b:
    build: .
    environment:
      - NODE_ID=node-b
      - REGION_CODE=RU-TVE
      - PEERS=http://node-a:8080,http://node-c:8080
      - AI_BASE_URL=https://openrouter.ai/api/v1
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=deepseek/deepseek-chat
    volumes:
      - ./data/node-b:/app/data
    networks: [mesh]

  node-c:
    build: .
    environment:
      - NODE_ID=node-c
      - REGION_CODE=RU-SMO
      - PEERS=http://node-a:8080,http://node-b:8080
      - AI_BASE_URL=https://openrouter.ai/api/v1
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=deepseek/deepseek-chat
    volumes:
      - ./data/node-c:/app/data
    networks: [mesh]

networks:
  mesh:
    driver: bridge