services:
  node_a:
    build: .
    container_name: node_a
    environment:
      - NODE_ID=nodeA
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "8081:8080"
    volumes:
      - ./data/nodeA:/app/data

  node_b:
    build: .
    container_name: node_b
    environment:
      - NODE_ID=nodeB
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "8082:8080"
    volumes:
      - ./data/nodeB:/app/data

  node_c:
    build: .
    container_name: node_c
    environment:
      - NODE_ID=nodeC
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "8083:8080"
    volumes:
      - ./data/nodeC:/app/data